forge "https://forgeapi.puppetlabs.com"

mod "puppetlabs/puppetlabs-haproxy",
  :git => "https://github.com/puppetlabs/puppetlabs-haproxy",
  :ref => 'master'

mod "lefred/postgresqlbdr",
  :git =>  "https://github.com/lefred/puppet-lefred-postgresqldbr",
  :ref => 'master'


